In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
store_cleaned = pd.read_csv(r'E:\data-science-projects\Rossmann Store Sales\data\processed\store_cleaned.csv')
train_cleaned = pd.read_csv(r'E:\data-science-projects\Rossmann Store Sales\data\processed\train_cleaned.csv')
test_cleaned = pd.read_csv(r'E:\data-science-projects\Rossmann Store Sales\data\processed\test_cleaned.csv')

C:\Users\HP\AppData\Local\Temp\ipykernel_3708\434394389.py:2: DtypeWarning: Columns (0: StateHoliday) have mixed types. Specify dtype option on import or set low_memory=False.
  train_cleaned = pd.read_csv(r'E:\data-science-projects\Rossmann Store Sales\data\processed\train_cleaned.csv')

In [9]:
store_cleaned.head()

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
2,3,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
3,4,c,c,620.0,9.0,2009.0,0,NaN,NaN,NaN
4,5,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN

In [6]:
store_cleaned.columns

Index(['Store', 'StoreType', 'Assortment', 'CompetitionDistance',
       'CompetitionOpenSinceMonth', 'CompetitionOpenSinceYear', 'Promo2',
       'Promo2SinceWeek', 'Promo2SinceYear', 'PromoInterval'],
      dtype='str')

In [7]:
store_cleaned.isnull().sum()

Store                          0
StoreType                      0
Assortment                     0
CompetitionDistance            3
CompetitionOpenSinceMonth    354
CompetitionOpenSinceYear     354
Promo2                         0
Promo2SinceWeek              544
Promo2SinceYear              544
PromoInterval                544
dtype: int64

In [8]:
store_cleaned['CompetitionDistance'].fillna(store_cleaned['CompetitionDistance'].median(), inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_3708\1421491701.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  store_cleaned['CompetitionDistance'].fillna(store_cleaned['CompetitionDistance'].median(), inplace=True)

0        1270.0
1         570.0
2       14130.0
3         620.0
4       29910.0
         ...
1110     1900.0
1111     1880.0
1112     9260.0
1113      870.0
1114     5350.0
Name: CompetitionDistance, Length: 1115, dtype: float64

In [10]:
cols = ['CompetitionOpenSinceMonth','CompetitionOpenSinceYear','Promo2SinceWeek','Promo2SinceYear']
store_cleaned[cols].fillna(0, inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_3708\350806229.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  store_cleaned[cols].fillna(0, inplace=True)

,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2SinceWeek,Promo2SinceYear
0,9.0,2008.0,0.0,0.0
1,11.0,2007.0,13.0,2010.0
2,12.0,2006.0,14.0,2011.0
3,9.0,2009.0,0.0,0.0
4,4.0,2015.0,0.0,0.0
...,...,...,...,...
1110,6.0,2014.0,31.0,2013.0
1111,4.0,2006.0,0.0,0.0
1112,0.0,0.0,0.0,0.0
1113,0.0,0.0,0.0,0.0
1114,0.0,0.0,22.0,2012.0

In [11]:
store_cleaned['PromoInterval'].fillna('None', inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_3708\672978277.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  store_cleaned['PromoInterval'].fillna('None', inplace=True)

0                   None
1        Jan,Apr,Jul,Oct
2        Jan,Apr,Jul,Oct
3                   None
4                   None
              ...
1110     Jan,Apr,Jul,Oct
1111                None
1112                None
1113                None
1114    Mar,Jun,Sept,Dec
Name: PromoInterval, Length: 1115, dtype: str

In [ ]:
train_cleaned['Sales'].hist(bins=50)
plt.show()

np.int64(0)